CREATE DATABASE IF NOT EXISTS COMERCIO;
USE COMERCIO;

CREATE TABLE TIENDA (
    NIF VARCHAR(10),
    NOMBRE VARCHAR(20),
    DIRECCION VARCHAR(20),
    POBLACION VARCHAR(20),
    PROVINCIA VARCHAR(20),
    CODPOSTAL INT,
    CONSTRAINT PK_CIF PRIMARY KEY (NIF),
    CONSTRAINT MAYUSCULA CHECK (NOMBRE = UPPER(NOMBRE)),
    CONSTRAINT NOMBRE_NULL CHECK (NOMBRE IS NOT NULL)
);

CREATE TABLE FABRICANTE (
    COD_FABRICANTE INT(5),
    NOMBRE VARCHAR(15),
    PAIS VARCHAR(15),
    CONSTRAINT CODFAB_PG PRIMARY KEY (COD_FABRICANTE),
    CONSTRAINT NOMBRE_MAYUSCULA CHECK (NOMBRE = UPPER(NOMBRE)),
    CONSTRAINT PAIS_MAYUSCULA CHECK (PAIS = UPPER(PAIS))
);

CREATE TABLE ARTICULO (
    ARTICULO VARCHAR(20),
    COD_FABRICANTE INT(5),
    PESO INT(3),
    CATEGORIA VARCHAR(10),
    PRECIO_VENTA DECIMAL(6.2),
    PRECIO_COSTO DECIMAL(6.2),
    EXISTENCIAS INT(5),
    CONSTRAINT FK_CODFAB FOREIGN KEY (COD_FABRICANTE)
        REFERENCES FABRICANTE (COD_FABRICANTE)
        ON DELETE CASCADE,
    CONSTRAINT PK_CLAVEP PRIMARY KEY (ARTICULO , COD_FABRICANTE , PESO , CATEGORIA),
    CONSTRAINT MAYORQUE0 CHECK (PRECIO_VENTA > 0 AND PRECIO_COSTO > 0
        AND PESO > 0),
    CONSTRAINT CATEGORIA_ CHECK (CATEGORIA IN ('PRIMERA' , 'SEGUNDA', 'TERCERA'))
);

CREATE TABLE VENTA (
    NIF VARCHAR(10),
    ARTICULO VARCHAR(20),
    COD_FABRICANTE INT(5),
    PESO INT(3),
    CATEGORIA VARCHAR(10),
    FECHA_VENTA DATE,
    UNIDADES_VENDIDAS INT(4),
    CONSTRAINT PK_CLAVEPV PRIMARY KEY (NIF , ARTICULO , COD_FABRICANTE , PESO , CATEGORIA , FECHA_VENTA),
    CONSTRAINT VENDIDAS_MAY0 CHECK (UNIDADES_VENDIDAS > 0),
    CONSTRAINT CATEGORIV CHECK (CATEGORIA IN ('PRIMERA' , 'SEGUNDA', 'TERCERA')),
    CONSTRAINT FK_CLAVEAJEV FOREIGN KEY (ARTICULO , COD_FABRICANTE , PESO , CATEGORIA)
        REFERENCES ARTICULO (ARTICULO , COD_FABRICANTE , PESO , CATEGORIA)
        ON DELETE CASCADE,
    CONSTRAINT FK_NIFV FOREIGN KEY (NIF)
        REFERENCES TIENDA (NIF)
        ON DELETE CASCADE
);

CREATE TABLE PEDIDO (
    NIF VARCHAR(10),
    ARTICULO VARCHAR(20),
    COD_FABRICANTE INT(5),
    PESO INT(3),
    CATEGORIA VARCHAR(10),
    FECHA_PEDIDO DATE,
    UNIDADES_PEDIDAS INT(4),
    EXISTENCIAS INT(5),
    CONSTRAINT PK_CLAVEPP PRIMARY KEY (NIF , ARTICULO , COD_FABRICANTE , PESO , CATEGORIA , FECHA_PEDIDO),
    CONSTRAINT FK_CLAVENIFP FOREIGN KEY (NIF)
        REFERENCES TIENDA (NIF)
        ON DELETE CASCADE,
    CONSTRAINT FK_CLAVEAJEP FOREIGN KEY (ARTICULO , COD_FABRICANTE , PESO , CATEGORIA)
        REFERENCES ARTICULO (ARTICULO , COD_FABRICANTE , PESO , CATEGORIA)
        ON DELETE CASCADE,
    CONSTRAINT CATEGORIP CHECK (CATEGORIA IN ('PRIMERA' , 'SEGUNDA', 'TERCERA'))
);