CREATE DATABASE IF NOT EXISTS COMERCIO;
USE COMERCIO;

CREATE TABLE TIENDA(
NIF VARCHAR(10),
NOMBRE VARCHAR(20),
DIRECCION VARCHAR(20),
POBLACION VARCHAR(20),
PROVINCIA VARCHAR(20),
CODPOSTAL INT
);

ALTER TABLE TIENDA ADD CONSTRAINT PK_CIF PRIMARY KEY (NIF);
ALTER TABLE TIENDA ADD CONSTRAINT MAYUSCULA CHECK(NOMBRE=upper(NOMBRE));
ALTER TABLE TIENDA
MODIFY COLUMN NOMBRE VARCHAR (20) NOT NULL;

CREATE TABLE FABRICANTE(
COD_FABRICANTE INT(5),
NOMBRE VARCHAR(15),
PAIS VARCHAR(15)
);

ALTER TABLE FABRICANTE ADD CONSTRAINT CODFAB_PG PRIMARY KEY (COD_FABRICANTE);
ALTER TABLE FABRICANTE ADD CONSTRAINT NOMBRE_MAYUSCULA CHECK (NOMBRE=UPPER(NOMBRE));
ALTER TABLE FABRICANTE ADD CONSTRAINT PAIS_MAYUSCULA CHECK (PAIS=UPPER(PAIS));

CREATE TABLE ARTICULO(
ARTICULO VARCHAR(20),
COD_FABRICANTE INT(5),
PESO INT(3),
CATEGORIA VARCHAR(10),
PRECIO_VENTA DECIMAL(6.2),
PRECIO_COSTO DECIMAL(6.2),
EXISTENCIAS INT(5)
);

ALTER TABLE ARTICULO ADD CONSTRAINT FK_CODFAB FOREIGN KEY (COD_FABRICANTE)
REFERENCES FABRICANTE (COD_FABRICANTE) ON DELETE CASCADE;
ALTER TABLE ARTICULO ADD CONSTRAINT PK_CLAVEP PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA);
ALTER TABLE ARTICULO ADD CONSTRAINT MAYORQUE0 CHECK (PRECIO_VENTA > 0 AND PRECIO_COSTO > 0 AND PESO > 0);
ALTER TABLE ARTICULO ADD CONSTRAINT CATEGORIA_ CHECK (CATEGORIA IN ('PRIMERA', 'SEGUNDA', 'TERCERA'));

CREATE TABLE VENTA(
NIF VARCHAR(10),
ARTICULO VARCHAR(20),
COD_FABRICANTE INT(5),
PESO INT(3),
CATEGORIA VARCHAR(10),
FECHA_VENTA DATE,
UNIDADES_VENDIDAS INT(4)
);
ALTER TABLE VENTA ADD CONSTRAINT PK_CLAVEPV PRIMARY KEY(NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA,FECHA_VENTA);
ALTER TABLE VENTA ADD CONSTRAINT VENDIDAS_MAY0 CHECK (UNIDADES_VENDIDAS > 0);
ALTER TABLE VENTA ADD CONSTRAINT CATEGORIV CHECK (CATEGORIA IN ('PRIMERA', 'SEGUNDA', 'TERCERA'));
ALTER TABLE VENTA ADD CONSTRAINT FK_CLAVEAJEV FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULO(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) ON DELETE CASCADE;
ALTER TABLE VENTA ADD CONSTRAINT FK_NIFV FOREIGN KEY (NIF) REFERENCES TIENDA(NIF) ON DELETE CASCADE;

CREATE TABLE PEDIDO(
NIF VARCHAR(10),
ARTICULO VARCHAR(20),
COD_FABRICANTE INT(5),
PESO INT(3),
CATEGORIA VARCHAR(10),
FECHA_PEDIDO DATE,
UNIDADES_PEDIDAS INT(4),
EXISTENCIAS INT(5)
);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_CLAVEPP PRIMARY KEY(NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA,FECHA_PEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CLAVENIFP FOREIGN KEY (NIF) REFERENCES TIENDA(NIF) ON DELETE CASCADE;
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CLAVEAJEP FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULO(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) ON DELETE CASCADE;
ALTER TABLE PEDIDO ADD CONSTRAINT CATEGORIP CHECK (CATEGORIA IN ('PRIMERA', 'SEGUNDA', 'TERCERA'));